### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1543]
It would be great to release often, so that the changelog is manageable.

**Please comment if you have something you would like to get in this release.**

Release tasks:
* [ ] add entry to CHANGELOG
  * query to get CHANGELOG PRs:
    https://github.com/swarm-game/swarm/pulls?q=is%3Apr+closed%3A%3E2023-08-18+label%3ACHANGELOG
  * On cmdline: `gh pr list -s closed -S 'closed:>2023-08-18 label:CHANGELOG' | tr '\t' ',' > 0.5-changes.txt`
* [ ] tag Swarm version
* [ ] tag VSCode plugin
* [ ] write blog post on Swarm website

---

Previous release Issues:
* #1316
* #1012
* #666

**Comment by byorgey** [comment]
Good idea!  Ideally I'd like to get #1512 squared away first.  Need to get back to that.

Should we make some kind of target release schedule?  Nothing too rigid, but right now we just release "whenever someone thinks of it" but it might be nice to have a specific frequency to shoot for.

**Comment by xsebek** [comment]
@byorgey I think the ideal would be to release each “feature” or significant bug fix.

For example I would like to get code formatting to a usable state.

This also reminds me I need to finish VSCode plugin move to swarm-game.

**Comment by byorgey** [comment]
> I think the ideal would be to release each “feature” or significant bug fix.

That sounds like too much work though.  Even with all the great release automation we have, it's still work to make sure the changelog is formatted nicely, bump the version number, etc.  I don't want to go through all that every time we merge a feature or bug fix.  My idea was that if we have a target schedule (e.g. "we aim to make a new release on the 1st of every month" or "on the 15th of every even month" or "every other week", or whatever we decide the appropriate frequency is) then we can put it in our calendars and it will remind us to make more frequent releases.  And of course even if we do have a schedule we could always make extra releases when we do merge some big feature or significant bug fix.

**Comment by xsebek** [comment]
I would like to get #1479 merged, but the other fixes and improvements for `--format` can come later.

I moved VSCode to `swarm-game`, updated secrets and made @kostmo maintainer, so that should be good to go.

---

@byorgey @kostmo do you have anything else that you would like to wait for? 🙂 

Btw. I was thinking, whether we should write to CHANGELOG ourselves, so that it's less work to release? 🤔

**Comment by byorgey** [comment]
> do you have anything else that you would like to wait for? 🙂

Not me!

**Comment by kostmo** [comment]
> do you have anything else that you would like to wait for?

I'm nearly done with #1441, but I don't suppose it needs to hold up a release.

**Comment by byorgey** [comment]
0.5 release is away!  I guess someone still needs to do a VSCode release?  There is also a todo above to write a blog post, but I don't have the time or inclination to do that right now.  If someone else wants to take a shot at writing a blog post, go for it --- especially now that we have our own blog hosted on our shiny new website.  Just make a PR to https://github.com/swarm-game/swarm-game.github.io .
