### ISSUE TITLE
[Umbrella] More structure recognition enhancements

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1645]
Moved from #1579.

- [x] Refactor `State.hs` so that the new helper functions can live elsewhere (Prerequisites: #1667, #1669)
- [x] Support non-rectangular recognizable structures (Done: #1618, #1637)
- [ ] Create a recipe for the `blueprint` device. See also #2303 .
- [x] Allow flip/rotate of recognizable structures (#1644)
- [ ] Structure ownership by robots
- [ ] Consolidate code between the Goals and Structures modal dialogs, and the Achievements browser
- [ ] Enforce minimum/maximum dimensions for structure definitions
- [x] #1646
