### ISSUE TITLE
Release 0.6

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1940]
It's been a while, we should definitely do a new release!

**Please comment if you have something you would like to get in this release.**

Things to merge/solve before release:

- [x] #1928 
- [x] #1945 
- [x] #1888 
- [x] #1883 
- [x] #1622 ?
- [x] #1975
- [x] #1979 
- [x] #2009
- [x] #2027 

Release tasks:
* [x] #1970 #2039
* [x] bump version
* [x] make sure installation & contributing instructions are up to date
* [x] make sure community information is up to date (e.g. in light of #2009)
* [x] Play through tutorials to make sure we haven't accidentally introduced any regressions that new players might run into
* [ ] look into building OSX or Windows binaries?
* [x] Quickly skim through commits since 0.5 release (Nov 2023) to see if there are any that ought to be labeled `CHANGELOG` but are not 
* [x] add entry to CHANGELOG
  * query to get CHANGELOG PRs:
    https://github.com/swarm-game/swarm/pulls?q=is%3Apr+closed%3A%3E2023-11-01+label%3ACHANGELOG
  * On cmdline: `gh pr list -s closed -S 'closed:>2023-11-01 label:CHANGELOG' | tr '\t' ',' > 0.6-changes.txt`
* [x] regenerate wiki cheatsheets
* [ ] tag Swarm version
* [ ] tag VSCode plugin
* [ ] write blog post on Swarm website
* [ ] publicize blog post

---

Release PRs:
* #1980 
* https://github.com/swarm-game/swarm-game.github.io/pull/6

---

Previous release Issues:
* #1543 
* #1316
* #1012
* #666

**Comment by nitinprakash96** [comment]
> look into building OSX or Windows binaries?

Regarding OSX, do you mean to provide swarm executable as a homebrew formula? Or provide a binary via Github assets?

**Comment by byorgey** [comment]
I don't use OSX, so I don't even know what the options are.  Whatever would be an easy way for someone on OSX to be able to install some kind of pre-built version of Swarm.

**Comment by nitinprakash96** [comment]
I think we can do it in CI itself. Let me test out the theory. But in short, my idea was to build an executable using cabal on macos runner (macos-latest) in CI and then upload it to github assets.

**Comment by xsebek** [comment]
@nitinprakash96 I can help with Mac and Windows, as I have both.

@byorgey I would like to try to get the keybindings ready before release, but if it takes too long it can wait for the next release.

**Comment by byorgey** [comment]
> But in short, my idea was to build an executable using cabal on macos runner (macos-latest) in CI and then upload it to github assets.

Uploading an executable every single time we run CI seems wasteful (?).  But we have an existing `release` action where I think it would make sense to add this: https://github.com/swarm-game/swarm/blob/main/.github/workflows/haskell-release.yml (I think it needs to be updated anyway).

**Comment by byorgey** [comment]
> I would like to try to get the keybindings ready before release

@xsebek great!  Add it to the list in the description.

**Comment by nitinprakash96** [comment]
I managed to make an example CI workflow for mac releases https://github.com/nitinprakash96/HIsForHaskell/blob/main/.github/workflows/release.yml which adds an executable for mac in the releases section.

And this is close to the release CI job for swarm. Haven't tested windows though.
