### ISSUE TITLE
Design and implement more capabilities and devices

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#26]
There are quite a few capabilities that are missing; see the comments in [Swarm.Language.Capability](https://github.com/byorgey/swarm/blob/main/src/Swarm/Language/Capability.hs).  This will require some creative thinking and careful planning and testing.

---

Here is a list of commands and related issues (TODO):

- [x] **View** this should also require something. #17 
- [x] **Not**, **And**, **Or** some kind of boolean logic cap? #562
- [x] **Inl**, **Inr**, **Case** should require a capability for sums #563
- [x] **Fst**, **Snd** should require a cap for pairs #563
- [x] **Try** definitely needs to require something #132 
- [x] **Wait** could require **time** capability #402 

Here is the list of capabilities that are missing devices:

- [x] **senseloc** (Whereami)
- [x] **appear** (Appear) #1027 
- [x] **setname** (Setname) #1028 
- [ ] #1041
- [x] **random** (Random) #497
- [x] ~~**create**~~ (Create) make restricted instead in #408 
- [x] **compare** (==,!=,<, <=,>,>=) added with comparator in #395
- [x] **arith** (+,-,*,/) added with calculator in #362

Here is a list of devices that provide a capability but are missing a recipe (see also #361):

- [ ] #1017
- [x] **dictionary** #507 
- [x] **tool kit** #361 
- [x] **grabber** #507 
- [x] **3D printer** #496
- [x] **flash memory** #498
- [x] **treads** #434 

In addition, the following commands require **god** capability and are currently only intended for scenario development and not available to players (except for creative mode):
- **RobotNamed**, **RobotNumbered**
- **As**
- **Create**

---

Since #373 the exception users will see if there are no devices to provide required capability looks like this:
```
Missing the random capability for:
  'random'
 but no device yet provides it. See
 https://github.com/swarm-game/swarm/issues/26
```
Restricted commands give different message:
```
Thee shalt not utter such blasphemy:
  'as'
  If't be true thee wanteth to playeth god, then tryeth Creative game.
```

**Comment by xsebek** [comment]
I would really like to link the “counter” to a small solar panel and have a pocket calculator with arithmetic capability. 🧮

**Comment by byorgey** [comment]
I like that idea! =)  I had some vague thoughts about making an "ALU" but I like this better.  What should be the recipe for a solar panel?

**Comment by xsebek** [comment]
Sorry for the late reply @byorgey. I think solar panel mainly needs glass and some copper wires. It would be really nice to only add sand on water beaches, but I am not sure if the noise function in water terrain generation would work for that. Assuming we had sand, I imagine the recipes would be:

```
     furnace
sand ───┴─── glass

     3D printer
glass ──┬┴─── solar 
copper ─┘     panel
wires

     3D printer
counter ──┬┴─── calculator
solar ────┘
panel
```
I only used 3D-printer to look fancy and avoid making recipe for [cadmium telluride](https://en.wikipedia.org/wiki/Thin-film_solar_cell) or something like that. :smirk:

**Comment by byorgey** [comment]
Some additional ideas related to #361 .  I want to wait until #373 lands and then add these things.

- `quartz` can be mined.  From `quartz` one can make `silicon`; also `quartz` could be an ingredient for making a `clock`.
- `silicon` + `strange loop` + some number of `bit`s -> `circuit`
- Add red, green and blue pixel entities that grow and can be harvested, like bits
- `glass` + 10 `red pixel` + 10 `blue pixel` + 10 `green pixel` -> `camera`
- `camera` + `circuit` -> `scanner`

**Comment by byorgey** [comment]
Ideas for a device to give the `compare` capability: a `comparator` perhaps?

Recipe?
- 1 `branch predictor`
- 1 `balance scale`?  Not sure what the recipe would be for that
- Maybe something else?

I think we want comparison to be available pretty early.

**Comment by byorgey** [comment]
Didn't realize we have a `create` capability.  I always intended for `create` to be available only in creative mode, so maybe we should make it `CGod` also?

**Comment by byorgey** [comment]
I think we should just get rid of the `say` command, at least for now.  It used to do something but kind of got left behind when we added logger devices.

**Comment by xsebek** [comment]
@byorgey I was thinking `say` would become useful as a global God log (we could read `messageQueue` in some pop-up creative window) and check in the tests (no log required). Maybe other robots could hear you too if they are nearby and `listen`.

But `CCreate` and `raise` are definitely outdated, let me make a PR...

**Comment by xsebek** [comment]
How about making a `copper coin` and `iron coin` that would give the **random** capability?

**Comment by byorgey** [comment]
Or how about combining a `bit (0)` and `bit (1)` (+ maybe some `copper` or `iron ore`?) to make a `bitcoin` that gives the random capability? :grin:

**Comment by byorgey** [comment]
> I was thinking `say` would become useful as a global God log (we could read `messageQueue` in some pop-up creative window) and check in the tests (no log required). Maybe other robots could hear you too if they are nearby and `listen`.

Ah, those are all good ideas, let's keep it.

**Comment by byorgey** [comment]
Idea for `3D printer` recipe:
- `printer` (see #116)
- 5 `circuit`
- 1 `iron plate`
- 3 `copper pipe`
- 16 `iron gear`

**Comment by xsebek** [comment]
> **Run** this should also require a capability that the base starts with.

@byorgey do we need that? If #495 is implemented, the program will be inlined and checked for capabilities when hitting <kbd>Enter</kbd> in REPL. Unless I am missing something it should not give you any extra power than copy-pasting.

In particular, you would not be able to do:
```
waitForCommand <- build {require "rock"; until {run "put.sw";ishere "rock"}; grab; nowDoStuff};
// echo 'place "rock";' >> put.sw
```

**Comment by byorgey** [comment]
Oh, I totally agree with you.  I wrote that comment a while ago before thinking things through more in #495.

**Comment by xsebek** [comment]
I will also remove `say` from the list, as I am currently trying to revive it in #513 and it will be useful for it to not require any devices.

We can imagine that speaking is natural to robots, perhaps they just bang the robot shell or whizz with the motor to signal. :thinking:

**Comment by xsebek** [comment]
@byorgey you mentioned in #550 that water should be carried in some container - what do you think about using that instead of **detonator** to allow robots to `shortcircuit`?

**Comment by byorgey** [comment]
> @byorgey you mentioned in #550 that water should be carried in some container - what do you think about using that instead of **detonator** to allow robots to `shortcircuit`?

Pouring water on yourself to `shortcircuit` is funny, but it sounds to me like it would just make the robot halt, not cease to exist.  

Honestly self-destructing doesn't seem very useful except for system robots.  Maybe we should just make it a `CGod` thing and forget about `detonator`?

**Comment by xsebek** [comment]
I guess using `shortcircuit` as a weaker `halt` (#392) also makes sense, but once you pour water on an electric circuit it can be destroyed forever, so self-destruction seems also plausible to me.

I can imagine situations where you would want to get rid of the robot quickly without collecting it with `salvage`. Once we have the `meet` command (and later antennas) one robot left around could break your expectations and any protocol you built on them.

Also, it is just nice from an aesthetic standpoint - once I can create as many robots as I like, I will eventually not want to bother with salvaging them to clean my map view, unless they had an important task.

**Comment by xsebek** [comment]
While we no longer plan to _finish_ this issue for the Alpha release, it is IMO good to leave it pinned. :pushpin: 

If anyone has a good idea for devices/recipes feel free to discuss it here, in a separate Issue or on IRC. :slightly_smiling_face:

**Comment by byorgey** [comment]
There are only two items left (creating a device for `teleport`, and a recipe for `detonator`), neither is that important, and both have their own issue marked as "low hanging fruit".  I think I'm going to close this issue now, but anyone should feel free to reopen if there's a reason it would be helpful!
