### ISSUE TITLE
Create command line tools to automate documentation

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#344]
It would be nice to have either a separate executable or a new parameter to generate documentation.

Some ideas:

- [x] We have nice cheatsheets on the Wiki that are hard to keep up to date. Generate those markdown tables from code.
  - [x] **Commands** (name, type, capability, description) #531
  - [x] **Capabilities** (name, install, commands, description)
  - [x] **Entities** (character, name, capabilities, properties, portable)
  - [x] **Recipes** (in, out, required, time)
- [x] Recipe dependencies graph #476
- [x] Editor keywords  #526

**Comment by xsebek** [comment]
Also, there are the identifier lists in `editors/` that I did not update in a while :sweat_smile: 

- VS Code: [swarm.tmLanguage.json](https://github.com/swarm-game/swarm/blob/a6715e4bbde41a1d82ece7e77d3a17fe06a650ad/editors/vscode/syntaxes/swarm.tmLanguage.json#L59)
  ```json
  {
  "name": "keyword.operator",
  "match": "(<|>|==|<=|>=|!=|=|;|<-|-|\\+|\\*|\\^|\\$|/(?![/|*]))"
  },
  {
  "name": "keyword.other",
  "match": "\\b(?i)(noop|wait|selfdestruct|move|turn|grab|place|give|install|make|has|count|drill|build|salvage|reprogram|say|log|view|appear|create|whereami|blocked|scan|upload|ishere|whoami|random|run|if|inl|inr|case|fst|snd|force|return|try|raise|not)\\b"
  }
  ```
- Emacs: [swarm-mode.el](https://github.com/swarm-game/swarm/blob/a6715e4bbde41a1d82ece7e77d3a17fe06a650ad/editors/emacs/swarm-mode.el#L39)
  ```lisp
  (x-builtins '("if" "run" "return" "try" "raise" "force" "fst" "snd"))
  (x-commands
  '("noop" "wait" "selfdestruct" "move" "turn" "grab" "place" "give"
    "install" "make" "build" "salvage" "reprogram"
    "say" "log" "view" "appear" "create" "getx" "gety"
    "blocked" "scan" "upload" "ishere" "whoami"
    "random" "not"
    "left" "right" "back" "forward" "north" "south" "east" "west" "down"
    ))
  ```
  There is even a nice note: :spiral_notepad: 
  ```lisp
  ;; We should figure out how to autogenerate these, so we don't have
  ;; to edit the emacs mode every time we add new commands.
  ```

**Comment by xsebek** [comment]
We should figure out how to use [vty terminal mocking](https://hackage.haskell.org/package/vty-5.35.1/docs/Graphics-Vty-Output-Mock.html) or some other way to produce a text representation of the UI - this would be useful to draw recipes but also for testing and documentation.

**Comment by xsebek** [comment]
I think I will resume this next so that we can keep the whole Wiki up to date.

Making the recipe graph more useful is a separate problem, that I will finish later. It involves:
- #480 (will clean up the backward arrows)
- consider installed devices and inventory separately - I worked on this in #659 but got stuck

**Comment by xsebek** [comment]
How to render recipes:
- renderWidget: https://hackage.haskell.org/package/brick-1.4/docs/Brick-Main.html#v:renderWidget
- picImage: https://hackage.haskell.org/package/vty-5.37/docs/Graphics-Vty-Picture.html#v:picImage
- ???
- mockTerminal: https://hackage.haskell.org/package/vty-5.37/docs/Graphics-Vty-Output-Mock.html
- ???

Honestly I am not sure how to get just simple text.

**Comment by byorgey** [comment]
Good question.  We should ask @jtdaugherty.

**Comment by xsebek** [comment]
@byorgey I created an upstream issue for it:
-  jtdaugherty/brick#405

I wonder if there are other Widgets we would like to print.

---

However, I would like to close this issue and come back to the other improvements later.  🙂
