### ISSUE TITLE
Consider using GHC2021 extensions by default

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#419]
Let us discuss the `default-extensions` field in `swarm.cabal` - I suggest we put there all the extensions that we use a lot and that are harmless and not very interesting.

AFAIK we can not use [`GHC2021`](https://github.com/ghc-proposals/ghc-proposals/blob/ghc2021/proposals/0000-ghc2021.rst) yet, but it is the current "standard" way of writing Haskell, based on some collected statistics, community votes and a few votes by committee.

### PROs

- cleans up the module header
- highlights the more interesting extensions (looking at TH and undecidable instances :raised_eyebrow:)
- makes it easier to use nice syntax sugar anywhere we like

### CONs

- some bikeshedding could take place
- ?

## Extensions

Here are the extensions that we use in Swarm along with their count with those in GHC2021 checked:

- [ ] 1 AllowAmbiguousTypes
- [x] 1 BangPatterns
- [ ] 1 BlockArguments
- [ ] 1 DerivingStrategies
- [ ] 1 GADTs (we could use GADTSyntax which is in GHC2021, related #331) 
- [x] 1 ScopedTypeVariables
- [ ] 1 TemplateHaskellQuotes
- [ ] 2 DefaultSignatures
- [ ] 2 DerivingVia
- [x] 2 ImportQualifiedPost (we could require it with [-Wprepositive-qualified-module](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/using-warnings.html#ghc-flag--Wprepositive-qualified-module))
- [x] 2 NumericUnderscores
- [x] 3 DeriveFunctor
- [x] 3 DeriveTraversable
- [x] 3 TypeOperators
- [ ] 3 ViewPatterns
- [x] 4 StandaloneDeriving
- [ ] 4 TypeFamilies
- [ ] 4 UndecidableInstances
- [x] 5 DeriveDataTypeable
- [ ] 5 PatternSynonyms
- [ ] 5 QuasiQuotes
- [x] 6 DeriveAnyClass
- [x] 6 DeriveGeneric
- [x] 6 RankNTypes
- [x] 6 TupleSections
- [x] 8 FlexibleContexts
- [ ] 8 TemplateHaskell
- [ ] 9 LambdaCase (let's add this one too)
- [x] 10 MultiParamTypeClasses
- [x] 11 FlexibleInstances
- [x] 15 TypeApplications
- [ ] 20 OverloadedStrings

---

What do you think? :slightly_smiling_face:

**Comment by byorgey** [comment]
Sure, sounds fine to me.  It just makes it slightly harder for new contributors to figure out what is going on when reading the code.  But maybe we could solve that by putting a standard comment at the top of every module pointing to the `default-extensions` field?

**Comment by byorgey** [comment]
I like the idea of adding `-Wprepositive-qualified-module`.  Import lists read so much better with `ImportQualifiedPost`.

**Comment by byorgey** [comment]
I also like the idea of using `GADTSyntax` instead of `GADTs` where possible.

**Comment by xsebek** [comment]
The documentation aspect is a good point. Eventually, the situation will be reversed, because all that stuff will be on by default in GHCi with I think 9.2 (and possibly also 9.0.2?).

We could definitely cherry-pick those that are self-explanatory (deriving, numeric underscore,...) and keep those that are a bit weird and not well known explicitly in files. For example, TupleSection and LambdaCase are non-Haskell2010 but were so popular in our Haskell university course that I think they were eventually allowed. :smirk: 

> I like the idea of adding -Wprepositive-qualified-module. Import lists read so much better with ImportQualifiedPost.

It also works better with HLS until I fix it - I have an open PR there, that I should get back to... :sweat_smile: 

> I also like the idea of using GADTSyntax instead of GADTs where possible.

Totally, it was a nice discovery for me while I was reading about GHC2021. But we only use it in one place so far... :slightly_smiling_face:
