### ISSUE TITLE
Create Alpha release

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#666]
This issue shall serve as the final checklist of tasks for the Alpha release.

### Final issues

These are the last issues left to do in [our plan for Alpha](https://github.com/orgs/swarm-game/projects/1):

- #635 
- #609
- #611

### Final tasks
There are also a few small tasks we should do before releasing:
- [x] Update README :memo:
    - [x] More prominent links to IRC, wiki, COMMUNITY, + CONTRIBUTING near the top
    - [x] Recommend `cabal install swarm` in README
        #722
    - [x] Add an IRC badge/shield thing
- [x] Update CHANGELOG :memo: #727
- [x] Update https://github.com/swarm-game/swarm/wiki/Frequently-Asked-Questions,-Tips-and-Tricks ?
- [x] Make sure cheat sheets on wiki are up-to-date
- [x] Update Speedrun page on wiki
- [x] Bump Swarm version in Cabal :package: #727
  - the "pre-alpha" is named 0.0.0.1 so that current binaries can check and compare if a new release is available
- [x] Clean up tags :label: 
  - namely <kbd>Low hanging fruit</kbd> so its easier for others to join
- [x] Do a playthrough or two to catch any glaring problems
- [x] #673
  - it would be nice if everything was built automatically and pushed to Hackage and GitHub release
  - presumably, other projects have GitHub Actions that we could use for inspiration :slightly_smiling_face:
- [x] Add a bash snippet to release description explaining how to download the data dir.  See https://github.com/swarm-game/swarm/pull/678#issuecomment-1242975985
    #722 
- [x] Update issue templates and issue template chooser (links to other places to ask questions / give feedback?)
    - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

### Bugfixes

There were a few bugs that were found in the first release:
- [x] version comparison was not applied in released binaries (#729)
- [x] the scenario Swarm scripts were not searched for in the data directory (#730)

Let's quickly fix those and release a small bugfix release before publicizing Swarm:
- [x] Update CHANGELOG
- [x] Bump Cabal version
- [x] rename `data.zip` to something more descriptive
- [x] Push `0.1.0.1` tag (will automatically make a new release on GitHub and Hackage)

### Editor release

We should also publish a new version of the VSCode plugin with new keywords:
- [x] Update VSCode CHANGELOG
- [x] Push `swarm-language-vscode-0.0.7` tag

### Announcing

- [x] Add GitHub and Hackage release badges to README
      #725
- [x] Write announcement blog post :memo: 
- [x] Post announcement blog post
    https://byorgey.wordpress.com/2022/10/06/swarm-alpha-release/
- [x] Announce to r/haskell
    https://www.reddit.com/r/haskell/comments/xxeru1/swarm_alpha_release/

**Comment by byorgey** [comment]
How hard do you think it would be to create some binary builds for a few common architectures?  Is there an easy way to do that with GitHub Actions?  `cabal install` from Hackage is better than cloning the git repo and building from source, but it's still a big barrier for people who don't already have a Haskell toolchain installed.

**Comment by xsebek** [comment]
@byorgey I guess we will have to try and see. :slightly_smiling_face: 

I linked one blog post in #673, which has a GitHub Action that should do this automatically. :crossed_fingers: 
I can try it manually and check if those binaries will work in a clean docker container.
If not, then I will have to read more blog posts or ask around. :smile:

**Comment by xsebek** [comment]
:rocket: :tada:
